### ISSUE TITLE
NameError: name 'sock' is not defined

### ISSUE THREAD

**Issue by jyz0501** [pantomax/hassio-addons#4]
starting version 3.2.4
Requirement already up-to-date: broadlink in /usr/lib/python2.7/site-packages
Requirement already up-to-date: pyaes==1.6.0 in /usr/lib/python2.7/site-packages (from broadlink)
Traceback (most recent call last):
  File "/share/s1c.py", line 1, in <module>
    import broadlink
  File "/share/broadlink.py", line 609, in <module>
    sock.sendto(payload, ('255.255.255.255', 80))
NameError: name 'sock' is not defined

**Comment by jyz0501** [comment]
starting version 3.2.4
Requirement already up-to-date: broadlink in /usr/lib/python2.7/site-packages
Requirement already up-to-date: pyaes==1.6.0 in /usr/lib/python2.7/site-packages (from broadlink)
Traceback (most recent call last):
  File "/share/s1c.py", line 11, in <module>
    devices = broadlink.S1C(host=(broadlink_s1c_ip,80), mac=bytearray.fromhex(broadlink_s1c_mac)) # Change to your S1C IP Address and S1C Mac Address
ValueError: non-hexadecimal number found in fromhex() arg at position 2

**Comment by jyz0501** [comment]
starting version 3.2.4
Requirement already up-to-date: broadlink in /usr/lib/python2.7/site-packages
Requirement already up-to-date: pyaes==1.6.0 in /usr/lib/python2.7/site-packages (from broadlink)
Traceback (most recent call last):
  File "/share/s1c.py", line 14, in <module>
    sens = devices.get_sensors_status()
  File "/share/broadlink.py", line 551, in get_sensors_status
    _name = str(bytes(sens[4:26]).decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
